### PR TITLE
P3-273 Changes overview page

### PR DESCRIPTION
**Pull request by enricobattocchi**
## Context

* We want to allow users to check for changes between the original and a copy which is intented fo Rewrite & Republish. This should be similar to the WP revisions page, except that we just want to compare the current state of the original and of the copy without navigating the revision history.

## Summary

This PR can be summarized in the following changelog entry:

* Introduces a page to check changes for the Rewrite & Republish feature.

## Relevant technical choices:

* The issue was initially spec'd hinting at full re-use of the WP revisions feature. This proved to be unfeasible. We then decided to get the snippets of the differences, created by a WP function, and place them in a new page reusing some of the classes (and then styles) from WordPress. 
* An `Asset_Manager` class has been introduced to manage registering and enqueuing of JS and CSS files.
* The CSS files have been moved to a `css` folder.

### Test instructions for the acceptance test before the PR gets merged
This PR can be acceptance tested by following these steps:

#### Important:
* **This is just to test the main target of the PR**. Please also check for regressions (see below)

#### Steps - Block editor
* Edit a published post and make sure it has an excerpt.
* Create a Rewrite & Republish copy from that post.
* change the title, the content, the excerpt, then save with "Save as draft".
  * In the content try to make different types of changes: delete a paragraph, add a new one, change something in a sentence, remove an image, add a new one etc.
* click on "Republish" to open the sidebar with the publish checks. 
* Click on the `Do you want to compare your changes with the original version before merging?` link, introduced in #65
* See that you land on a page with the comparison of the differences in the title, the content and the excerpt
  * check that is displayed accordingly to [the design](https://www.sketch.com/s/2ec4254a-9529-4616-abe7-f6262c2ed6dd/a/mRo2Lg)
  * see that the changes between the original and the copy are displayed correctly
  * see that if you click on the title link above you are led to the edit of the Original (if you have the rights to do it)
  * see that if you click on "return to editor" you are brought back to the edit screen for the copy.
  
 #### Steps - Classic editor
* Activate classic editor
* Edit a published post and make sure it has an excerpt.
* Create a Rewrite & Republish copy from that post.
* change the title, the content, the excerpt, then save with "Save as draft".
  * In the content try to make different types of changes: delete a paragraph, add a new one, change something in a sentence, remove an image, add a new one etc.
* Click on the `Do you want to compare your changes with the original version before merging?` link, introduced in #65
* See that you land on a page with the comparison of the differences in the title, the content and the excerpt
  * check that is displayed accordingly to [the design](https://www.sketch.com/s/2ec4254a-9529-4616-abe7-f6262c2ed6dd/a/mRo2Lg)
  * see that the changes between the original and the copy are displayed correctly
  * see that if you click on the Title you are led to the edit of the Original (if you have the rights to do it)
  * see that if you click on "return to editor" you are brought back to the edit screen for the copy.

### Test instructions for QA when the code is in the RC

* [ ] QA should use the same steps as above.

QA can test this PR by following these steps:

* **Not applicable**   PR with extensive test instructions for the whole Rewrite and Republish feature (or for the whole plugin, to check for regressions etc.) will follow.

## Impact check

This PR affects the following parts of the plugin, which may require extra testing:

* While doing the tests above, please have a look if there have been breaking changes with the notices (#63 has an overview)

## UI changes

* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Documentation

* [ ] I have written documentation for this change.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [x] I have added unittests to verify the code works as intended

Fixes [P3-273]

### CODE REVIEW

**Comment by JesserH** [comment]
CR ✅

**Comment by karlijnbok** [comment]
Acceptance 🚧 

I found a few things:

1. Currently you have to save the draft of a Rewrite & Republish post before the changes overview works, as a "Leave site?" pop-up appears when you click the link and you have not saved your changes. I feel like this might not be completely clear for users. Because to fix this you first need to cancel the pop-up, then cancel the pre-publish screen, and then save the draft and go back. I feel like it could be made a bit clearer to users that the draft needs to be saved before you can check the changes. I am asking product what they think and will update on this PR when I have received some feedback ([link to slack discussion](https://yoast.slack.com/archives/C01BY0UMA1J/p1608718448035100)).
[See this loom for clarification of the problem](https://www.loom.com/share/5fb1697e52854ab79cfa9994e7b1b252) (in the block editor, but this is also the case in the classic editor).

2. In the changes overview, the quotation marks are missing around the post title.
Implementation vs design:
Screenshot 2020-12-23 at 10 18 53
Screenshot 2020-12-23 at 10 19 04

3. Somehow the distinction between the Title, Content and Excerpt section is not as obvious to me as it is in the design. Not sure whether you agree, but it would probably be a bit clearer with an extra blank line between the sections, or by making the headings a bit bigger/bolder. What do you think? (let me know if you want me to consult product)
Implementation vs design:
Screenshot 2020-12-23 at 10 38 06
Screenshot 2020-12-23 at 10 38 46

4. Something seems off when you try to schedule a post intended for republishing. Nothing seems to happen, no notice is shown that the post is scheduled and no notice is shown on the original post that the rewrite and republish copy has been scheduled.
[See this loom for clarification of the problem in the classic editor.](https://www.loom.com/share/ffb932516365408d96972fee8c082581)
[See this loom for clarification of the problem in the block editor.](https://www.loom.com/share/81e5a403b05d48ec861c481e20276d35)

5. When I make a change in the original post and then click "Update", a redirect is created (which should not happen...). And the notice stating that the original post has been edited is not shown on the copy. (this happens both for the classic and the block editor)
Screenshot 2020-12-23 at 10 51 51

**Comment by enricobattocchi** [comment]
1. Will be addressed pending decisions by Product and UX
2. Will fix

**Comment by enricobattocchi** [comment]
3. Discussed with @karlijnbok, the comparison of changes is actually the same (= uses the same functions and styles) as the WP revisions feature so we'll keep it as it is
Screenshot_2020-12-23 Revisions ‹ Basic — WordPress
Screenshot_2020-12-23 ‹ Basic — WordPress(1)

**Comment by enricobattocchi** [comment]
4. addressed by #74 (currently awaiting review)
5. this is an issue with the copying of the slug "as it is" which will need to be discussed with the team (related: P3-281)

**Comment by karlijnbok** [comment]
Acceptance 2: 👍 
The remaining problems are be handled in other issues, as mentioned in the comments above.

**Pull request merged**
