### PR TITLE
P3-251 Introduce autoloading and initial class folder structure

### PR DESCRIPTION
**Pull request by afercia**
## Context

* We want to ensure that future expansion of the code remains stable and testable by switching over to a class-based folder structure use autoloading in Composer.

## Summary

This PR can be summarized in the following changelog entry:

* Introduces class autoloading in Composer and initial class folder structure.

## Relevant technical choices:

Please note this is a first pass at implementing autoloading. There are some architectural choices that should be discussed with architects (e.g. folder structure, Coding Standards to use) and there are no tests for now.

- adds a basic autoloading implementation
- adds initial class folder structure: note that at the moment the file names and class names are based on the WordPress PHPCS
- adds the class folder to the coding standards checks
- introduces a main class `Duplicate_Post`
- introduces a class `Duplicate_Post_User_Interface` meant to handle the plugin user interface
- moves some existing code into the `Duplicate_Post_User_Interface`:
  - for now, moves only the code related to the "Rewrite & Republish" link displayed in the Gutenberg sidebar
  - I opted to not move other code because it seems to me it's a bit intertwined with the legacy code
  - note: not sure whether the call to `duplicate_post_get_clone_post_link` in `Duplicate_Post_User_Interface` at line 66 is correct, please double check

### Test instructions for the acceptance test before the PR gets merged
This PR can be acceptance tested by following these steps:

- run `composer install`, `yarn`, and `grunt build:js` to build the plugin
- run `composer check-cs` and observe there are only warnings related to pre-existing code
- activate the plugin
- edit a gutenberg **published** post
- observe there is a link "Rewrite & Republish" in the gutenberg sidebar (above "Mote to trash")
- check in your console there are no JS errors related to this link
- check the link works correctly: click on it and check it generates a copy of the post and redirects you to the copy

### Test instructions for QA when the code is in the RC

* [ ] QA should use the same steps as above.

QA can test this PR by following these steps:

- No test instructions for QA: it was agreed this feature should be checked as a whole when implementation is complete.

## Impact check

This PR affects the following parts of the plugin, which may require extra testing:

*

## UI changes

* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Documentation

* [ ] I have written documentation for this change.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes [P3-251]

### CODE REVIEW

**Comment by afercia** [comment]
Note: the Travis build was failing because Travis automatically installs Composer 2.0 now. I tried to follow what was done for Premium and Free (see for example https://github.com/Yoast/wordpress-seo-premium/pull/3060) and downgraded composer only for the job that runs the CS. I'd appreciate some Travis specialist to review this part 🙂

**Comment by karlijnbok** [comment]
CR: 👍 
The namespaces still have to be added.

**Comment by enricobattocchi** [comment]
Added `use` statement in main plugin file to use namespaced autoloaded class.
This means we have to drop compatibility with PHP < 5.3.

**Comment by enricobattocchi** [comment]
Acceptance test OK, merging

**Pull request merged**
